version: '3'

services:
    app:
        restart: unless-stopped
        build: ./app
        expose: 
            - "8000"
        links: 
            - postgres:postgres
            - nginx:nginx
        volume
            
 