FROM debian:9 as build
RUN apt update && \
    apt install -y \
        wget \
        gcc \
        make  \
        libpcre3 \
        libpcre3-dev \
        zlib1g \
        zlib1g-dev \
        libssl-dev

CMD ["/bin/bash"]
