version: '3'
# https://docs.docker.com/compose/compose-file/compose-file-v3
# https://docs.docker.com/compose/networking/
services:
    app:
        restart: unless-stopped
        build: ./app
        expose: 
            - "8000"
        container_name: less11_app
        volumes: 
            - django_blog:/app/
            - django_static:/app/static/
        networks: 
                - netfront
                - netback
        depends_on: 
            - db
    web:
        restart: unless-stopped
        image: nginx:1.20-alpine
        volumes: 
            - ./app/django_blog/config/nginx/django.conf:/etc/nginx/conf.d/default.conf:ro
            - django_static:/src/static/
        ports:
            - "8000:8000"
        container_name: less11_web
        networks: 
            - netfront
    db:
        restart: always
        image: postgres:12.0-alpine
        volumes: 
            - postgres_data:/var/lib/postgresql/data
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        ports: 
            - "5432:5432"
        container_name: less11_db   
        networks: 
            - netfront
            - netback         

volumes: 
    postgres_data:
            name: less11_postgres_data
    django_blog:
        external: 
            name: django_blog
    django_static:
        external: 
            name: django_static

networks: 
    netback:            
        driver: bridge
        external: 
            name: DjangoBlog_back
    netfront:
        driver: bridge
        external: 
            name: DjangoBlog_front
